@WebApp_HostAddress = https://localhost:7277

POST {{WebApp_HostAddress}}/todoitems
Content-Type: application/json

{
  "task":"walk dog",
  "isCompleted":true
}

###

GET {{WebApp_HostAddress}}/todoitems

###

GET {{WebApp_HostAddress}}/todoitems/1

###

PUT {{WebApp_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "task":"walk dog",
  "isCompleted":false
}
###

DELETE {{WebApp_HostAddress}}/todoitems/1

###
